import csv
import json
import os

#convert a csv generated by create_pattern.py into a json
def create_pulsepattern(dir, band):
    "band: bass = 1, mid = 2, treble = 3"
    data = []
    with open(dir, 'r') as f:
        reader = csv.reader(f)
        next(reader)  # skip header
        for i in reader:
            data.append(i)

    roundedpoints = []
    roundedlist = []
    for datapoint in data:
        for thing in datapoint:
            roundedpoints.append(round(float(thing), 2))
        roundedlist.append(roundedpoints)
        roundedpoints = []

    bandlist_no_t = []
    for datapoint in roundedlist:
        bandlist_no_t.append(datapoint[band])

    maxval = max(bandlist_no_t)
    multipler = maxval**-1
    pulse_pattern = []
    for datapoint in roundedlist:
        pulse_pattern.append(
            (datapoint[0] * 1000, datapoint[band] * multipler))

    with open('pattern.json', 'w') as f:
        json.dump(pulse_pattern, f)


create_pulsepattern('audio_bands.csv', 3)
